app = 'fly-katia-ollama'
primary_region = 'ams'

[build]
  image = 'ollama/ollama:latest'

[[mounts]]
  source = 'ollama'
  destination = '/root/.ollama'
  initial_size = '10gb'

[http_service]
  internal_port = 11434
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'a100-80gb'
